language: csharp
os:
 - osx
 - linux
compiler:
  - clang
  - gcc
before_script:
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys D43A795B73B16ABE9643FE1AFD8FFF16DB45C6AB
  - echo "deb http://pkg.mxe.cc/repos/apt/debian wheezy main" | sudo tee -a /etc/apt/sources.list.d/mxeapt.list
  - apt-get -yy update
  - apt-get --assume-yes install mxe-i686-w64-mingw32.static-qt
script:
  - mkdir build
  - cd build
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cmake -DCMAKE_OSX_ARCHITECTURES="i386;x86_64" .. ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cmake .. ; fi
  - make
  - cd ..
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./buildwin64 ; fi
