language: csharp
os:
 - osx
 - linux
compiler:
  - clang
  - gcc
script:
  - mkdir build
  - cd build
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cmake -DCMAKE_OSX_ARCHITECTURES="i386;x86_64" .. ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cmake .. ; fi
  - make
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./buildwin64 ; fi
