#!/bin/bash
mkdir buildwin
cd buildwin
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys D43A795B73B16ABE9643FE1AFD8FFF16DB45C6AB
echo "deb http://pkg.mxe.cc/repos/apt/debian wheezy main" > /etc/apt/sources.list.d/mxeapt.list
apt-get -yy update
apt-get install -y mxe-i686-w64-mingw32.static-qt
target=i686-w64-mingw32.static
mxedir=/usr/lib/mxe/
$mxedir/usr/bin/$target-cmake ..
make
