#!/bin/bash
cd buildwin
target=i686-w64-mingw32.static
mxedir=/usr/lib/mxe
$mxedir/usr/bin/$target-cmake -DCMAKE_CXX_FLAGS="-fpermissive" ..
make
cp libmojoshader.dll ../build/libmojoshader_32.dll
rm -Rf *
target=x86-64-w64-mingw32.static
ls $mxedir/usr/bin/*-cmake
$mxedir/usr/bin/$target-cmake -DCMAKE_CXX_FLAGS="-fpermissive" ..
make
cp libmojoshader.dll ../build/libmojoshader_64.dll
